#!/usr/bin/env python3
"""Add computation metadata to .dvc files.

Reads existing .dvc files, computes dependency hashes, and writes back
with meta.computation blocks so `dvx run` can regenerate artifacts.
"""
from hashlib import md5
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
WWW_PUBLIC = ROOT / "www" / "public"

YEARS = range(2012, 2026)
HOURLY_YEARS = range(2017, 2023)


def file_md5(path: Path) -> str:
    h = md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def read_dvc_md5(dvc_path: Path) -> str:
    """Read the md5 from a .dvc file."""
    with open(dvc_path) as f:
        data = yaml.safe_load(f)
    return data["outs"][0]["md5"]


def update_dvc_file(dvc_path: Path, cmd: str, deps: dict[str, str]):
    """Add computation metadata to an existing .dvc file."""
    with open(dvc_path) as f:
        data = yaml.safe_load(f)

    data["meta"] = {
        "computation": {
            "cmd": cmd,
            "deps": deps,
        }
    }

    with open(dvc_path, "w") as f:
        yaml.dump(data, f, sort_keys=False, default_flow_style=False)


def main():
    # --- Per-year parquets ---
    # `path-data update -y {year}` produces {year}.pqt and {year}-day-types.pqt
    # deps: the monthly ridership PDF + monthly.ipynb
    nb_md5 = file_md5(ROOT / "monthly.ipynb")

    for year in YEARS:
        pdf = DATA / f"{year}-PATH-Monthly-Ridership-Report.pdf"
        if not pdf.exists():
            print(f"Skipping {year}: no PDF")
            continue

        pdf_md5 = file_md5(pdf)
        cmd = f"papermill monthly.ipynb out/monthly-{year}.ipynb -p year {year}"
        deps = {
            f"data/{year}-PATH-Monthly-Ridership-Report.pdf": pdf_md5,
            "monthly.ipynb": nb_md5,
        }

        for suffix in [f"{year}.pqt", f"{year}-day-types.pqt"]:
            dvc_path = DATA / f"{suffix}.dvc"
            if dvc_path.exists():
                update_dvc_file(dvc_path, cmd, deps)
                print(f"Updated {dvc_path.relative_to(ROOT)}")

    # --- Hourly parquets ---
    # Generated by analyze-hourly.ipynb; deps: hourly PDF + notebook
    hourly_nb = ROOT / "analyze-hourly.ipynb"
    if hourly_nb.exists():
        hourly_nb_md5 = file_md5(hourly_nb)
        for year in HOURLY_YEARS:
            pdf = DATA / f"{year}-PATH-Hourly-Ridership-Report.pdf"
            if not pdf.exists():
                continue
            pdf_md5 = file_md5(pdf)
            cmd = f"papermill analyze-hourly.ipynb out/analyze-hourly-{year}.ipynb -p year {year}"
            deps = {
                f"data/{year}-PATH-Hourly-Ridership-Report.pdf": pdf_md5,
                "analyze-hourly.ipynb": hourly_nb_md5,
            }
            for pattern in [f"{year}-hourly.pqt", f"{year}-hourly-system.pqt", f"{year}-hourly-total.pqt"]:
                dvc_path = DATA / f"{pattern}.dvc"
                if dvc_path.exists():
                    update_dvc_file(dvc_path, cmd, deps)
                    print(f"Updated {dvc_path.relative_to(ROOT)}")

    # --- Combined outputs ---
    # `path-data combine` runs months.ipynb, producing:
    #   data/all.pqt, data/all.xlsx
    #   www/public/all.pqt, www/public/{weekdays,weekends,avg_*}.json
    # deps: all per-year parquets + months.ipynb
    months_nb_md5 = file_md5(ROOT / "months.ipynb")
    deps = {"months.ipynb": months_nb_md5}
    for year in YEARS:
        dvc_path = DATA / f"{year}.pqt.dvc"
        if dvc_path.exists():
            deps[f"data/{year}.pqt"] = read_dvc_md5(dvc_path)

    combine_cmd = "papermill months.ipynb months.ipynb && cp data/all.pqt www/public/all.pqt"

    combine_outputs = [
        DATA / "all.pqt.dvc",
        DATA / "all.xlsx.dvc",
        WWW_PUBLIC / "all.pqt.dvc",
        WWW_PUBLIC / "weekdays.json.dvc",
        WWW_PUBLIC / "weekends.json.dvc",
        WWW_PUBLIC / "avg_weekday_month_grouped.json.dvc",
        WWW_PUBLIC / "avg_weekend_month_grouped.json.dvc",
    ]

    for dvc_path in combine_outputs:
        if dvc_path.exists():
            update_dvc_file(dvc_path, combine_cmd, deps)
            print(f"Updated {dvc_path.relative_to(ROOT)}")

    # --- Legacy/misc parquets (no computation - manual/one-off) ---
    for name in ["ezpass.pqt", "traffic.pqt"]:
        dvc_path = DATA / f"{name}.dvc"
        if dvc_path.exists():
            print(f"Skipped {dvc_path.relative_to(ROOT)} (no known computation)")


if __name__ == "__main__":
    main()
