#!/usr/bin/env python3
"""Add computation metadata to .dvc files.

Reads existing .dvc files, computes dependency hashes, and writes back
with meta.computation blocks so `dvx run` can regenerate artifacts.

Uses `deps` (content MD5) for DVX-tracked dependencies and `git_deps`
(blob SHA) for git-tracked dependencies.
"""
import subprocess
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
WWW_PUBLIC = ROOT / "www" / "public"

YEARS = range(2012, 2026)
HOURLY_YEARS = range(2017, 2023)


def git_blob_shas() -> dict[str, str]:
    """Get all blob SHAs from HEAD via `git ls-tree`."""
    result = subprocess.run(
        ["git", "ls-tree", "-r", "--format=%(objectname) %(path)", "HEAD"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    shas = {}
    for line in result.stdout.strip().split('\n'):
        if line:
            sha, path = line.split(' ', 1)
            shas[path] = sha
    return shas


def read_dvc_md5(dvc_path: Path) -> str:
    """Read the md5 from a .dvc file."""
    with open(dvc_path) as f:
        data = yaml.safe_load(f)
    return data["outs"][0]["md5"]


def update_dvc_file(
    dvc_path: Path,
    cmd: str,
    deps: dict[str, str] | None = None,
    git_deps: dict[str, str] | None = None,
):
    """Add computation metadata to an existing .dvc file."""
    with open(dvc_path) as f:
        data = yaml.safe_load(f)

    computation: dict = {"cmd": cmd}
    if deps:
        computation["deps"] = deps
    if git_deps:
        computation["git_deps"] = git_deps

    data["meta"] = {"computation": computation}

    with open(dvc_path, "w") as f:
        yaml.dump(data, f, sort_keys=False, default_flow_style=False)


def main():
    shas = git_blob_shas()

    # --- Per-year parquets ---
    # `path-data update -y {year}` produces {year}.pqt and {year}-day-types.pqt
    # git_deps: the monthly ridership PDF + monthly.ipynb
    for year in YEARS:
        pdf_path = f"data/{year}-PATH-Monthly-Ridership-Report.pdf"
        if pdf_path not in shas:
            print(f"Skipping {year}: no PDF in git")
            continue

        cmd = f"papermill monthly.ipynb out/monthly-{year}.ipynb -p year {year}"
        git_dep = {
            pdf_path: shas[pdf_path],
            "monthly.ipynb": shas["monthly.ipynb"],
        }

        for suffix in [f"{year}.pqt", f"{year}-day-types.pqt"]:
            dvc_path = DATA / f"{suffix}.dvc"
            if dvc_path.exists():
                update_dvc_file(dvc_path, cmd, git_deps=git_dep)
                print(f"Updated {dvc_path.relative_to(ROOT)}")

    # --- Hourly parquets ---
    # Generated by analyze-hourly.ipynb; git_deps: hourly PDF + notebook
    hourly_nb_path = "analyze-hourly.ipynb"
    if hourly_nb_path in shas:
        for year in HOURLY_YEARS:
            pdf_path = f"data/{year}-PATH-Hourly-Ridership-Report.pdf"
            if pdf_path not in shas:
                continue
            cmd = f"papermill analyze-hourly.ipynb out/analyze-hourly-{year}.ipynb -p year {year}"
            git_dep = {
                pdf_path: shas[pdf_path],
                hourly_nb_path: shas[hourly_nb_path],
            }
            for pattern in [f"{year}-hourly.pqt", f"{year}-hourly-system.pqt", f"{year}-hourly-total.pqt"]:
                dvc_path = DATA / f"{pattern}.dvc"
                if dvc_path.exists():
                    update_dvc_file(dvc_path, cmd, git_deps=git_dep)
                    print(f"Updated {dvc_path.relative_to(ROOT)}")

    # --- Combined outputs ---
    # `path-data combine` runs months.ipynb, producing:
    #   data/all.pqt, data/all.xlsx
    #   www/public/all.pqt, www/public/{weekdays,weekends,avg_*}.json
    # deps: all per-year parquets (DVX-tracked, content MD5)
    # git_deps: months.ipynb (git-tracked, blob SHA)
    dvx_deps = {}
    for year in YEARS:
        dvc_path = DATA / f"{year}.pqt.dvc"
        if dvc_path.exists():
            dvx_deps[f"data/{year}.pqt"] = read_dvc_md5(dvc_path)

    git_dep = {"months.ipynb": shas["months.ipynb"]}

    combine_cmd = "papermill months.ipynb months.ipynb && cp data/all.pqt www/public/all.pqt"

    combine_outputs = [
        DATA / "all.pqt.dvc",
        DATA / "all.xlsx.dvc",
        WWW_PUBLIC / "all.pqt.dvc",
        WWW_PUBLIC / "weekdays.json.dvc",
        WWW_PUBLIC / "weekends.json.dvc",
        WWW_PUBLIC / "avg_weekday_month_grouped.json.dvc",
        WWW_PUBLIC / "avg_weekend_month_grouped.json.dvc",
    ]

    for dvc_path in combine_outputs:
        if dvc_path.exists():
            update_dvc_file(dvc_path, combine_cmd, deps=dvx_deps, git_deps=git_dep)
            print(f"Updated {dvc_path.relative_to(ROOT)}")

    # --- Legacy/misc parquets (no computation - manual/one-off) ---
    for name in ["ezpass.pqt", "traffic.pqt"]:
        dvc_path = DATA / f"{name}.dvc"
        if dvc_path.exists():
            print(f"Skipped {dvc_path.relative_to(ROOT)} (no known computation)")


if __name__ == "__main__":
    main()
