name: Update data
on:
  workflow_dispatch:
  schedule:
    # Run every day at 9am (UTC)
    - cron: '0 9 * * *'
env:
  GIT_AUTHOR_NAME: "GitHub Actions"
  GIT_AUTHOR_EMAIL: "path-ridership-data@hudcostreets.org"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
jobs:
  update:
    name: Update PATH data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11.8
          cache: pip
      - run: pip install -e .
      - run: path-data refresh -cc
      - run: path-data update -cc
      - run: path-data combine -cc
      - run: aws s3 sync data/all.pqt s3://hudcostreets/path/
